---
- hosts: epel-centos5
  gather_facts: false
  tasks:
    - name: install packages for ansible support
      raw: yum -y install python-simplejson
      changed_when: False


- hosts: all
  roles:
    - role: ansible-role-epel
      epel_repo_testing_enabled: true
  post_tasks:
    - name: install varnish from epel repo
      package:
        name: varnish
        state: present
