---
# tasks file for epel

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: epel

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: epel

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: epel
