---
# tasks file for epel

- name: Install EPEL package
  package:
    name: "epel-release"
    state: present
  tags: epel

- name: epel_repo_enabled
  ini_file:
      path: /etc/yum.repos.d/epel.repo
      section: epel
      option: enabled
      value: "{{ epel_repo_enabled | lower }}"

- name: epel_repo_debuginfo_enabled
  ini_file:
      path: /etc/yum.repos.d/epel.repo
      section: epel-debuginfo
      option: enabled
      value: "{{ epel_repo_debuginfo_enabled | lower }}"

- name: epel_repo_source_enabled
  ini_file:
      path: /etc/yum.repos.d/epel.repo
      section: epel-source
      option: enabled
      value: "{{ epel_repo_source_enabled | lower }}"

- name: epel_repo_testing_enabled
  ini_file:
      path: /etc/yum.repos.d/epel-testing.repo
      section: epel-testing
      option: enabled
      value: "{{ epel_repo_testing_enabled | lower }}"

- name: epel_repo_testing_debuginfo_enabled
  ini_file:
      path: /etc/yum.repos.d/epel-testing.repo
      section: epel-testing-debuginfo
      option: enabled
      value: "{{ epel_repo_testing_debuginfo_enabled | lower }}"

- name: epel_repo_testing_source_enabled
  ini_file:
      path: /etc/yum.repos.d/epel-testing.repo
      section: epel-testing-source
      option: enabled
      value: "{{ epel_repo_testing_source_enabled | lower }}"
